# Generated by Django 4.0.1 on 2022-01-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_pizzamodel_price'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.PositiveIntegerField()),
                ('customer_address', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer', verbose_name='Customer id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pizzamodel', verbose_name='Product id')),
            ],
        ),
    ]
