# Generated by Django 4.0.1 on 2022-01-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customer_orderlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='product_id',
            new_name='product',
        ),
    ]
