# Generated by Django 4.0.1 on 2022-01-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pizza title')),
                ('description', models.TextField(max_length=1023, verbose_name='Pizza description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pizza price')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
