# Generated by Django 4.0.1 on 2022-01-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_model',
            new_name='PizzaModel',
        ),
    ]
