# Generated by Django 4.0.1 on 2022-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_pizzamodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Pizza price'),
        ),
    ]
